# Generated by Django 2.0.5 on 2018-09-11 22:52

from django.db import migrations

def seed(apps, schema_editor):
    User = apps.get_model('flix_db', 'User')
    Flix = apps.get_model('flix_db', 'Flix')
    Like = apps.get_model('flix_db', 'Like')
    Raj = User(username="userRaj", password="userRaj1")
    Luke = User(username="userLuke", password="userLuke1")
    Raj.save()
    Luke.save()

    sharp_objects = Flix(name='Sharp Objects', backdrop_path="www.backdroppathtosharpobjects.com", poster_path="www.posterpathtosharpobects.com",
    overview="A woman faces her psycological demons while returning to her hometown to cover the story of two dead girls",
    movie_id=4567)
    sharp_objects.save()

    big_little_lies = Flix(name='Big Little Lies', backdrop_path="www.backdroppathtobiglittlelies.com", poster_path="www.posterpathtobiglittlelies.com", overview="The apparently perfect lives of three mothers of first graders unravel to the point of murder.", movie_id=4643)
    big_little_lies.save()

    user_like = Like(user=Luke, flix=sharp_objects)
    user_like.save()

    user_like = Like(user=Raj, flix=big_little_lies)
    user_like.save()

def fallow(apps, schema_editor):
    User = apps.get_model('flix_db', 'User')
    Flix = apps.get_model('flix_db', 'Flix')
    Like = apps.get_model('flix_db', 'Like')
    User.objects.all().delete()
    Flix.objects.all().delete()
    Like.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('flix_db', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]


